services:
  resume-upper:
    container_name: resume-upper
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./runtime:/runtime
      - .:/app
    restart: unless-stopped

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["pytest", "tests", "-vv"]
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
